version: "3"

services:
  deciphergame:
    build: .
    command: |
      sh -c "pnpm run dev"
    volumes:
      - ./app:/opt/app
      - node_volume:/opt/app/node_modules
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=True
      - BROWSER=None
    ports:
      - 3000:3000

volumes:
  node_volume: {}