name: Node.js Package

on:
  push:
    branches: 
      - test_build

defaults:
  run:
    working-directory: app

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - uses: simenandre/publish-with-pnpm@v1
        with:
          npm-auth-token: ${{ secrets.NPM_TOKEN }}
