name: publishing decipher game

on:
  push:
    branches: 
      - test_build

defaults:
  run:
    working-directory: app
env:
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup npmrc
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
          standalone: true
          package_json_file: app/package.json
          dest: ~/setup-pnpm

      - name: Build
        run: |
          pnpm config set store-dir $PNPM_CACHE_FOLDER
          pnpm install
          pnpm build

      - name: Publish
        run: npm publish --provenance --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
