name: Node.js Package

on:
  push:
    branches: 
      - test_build

defaults:
  run:
    working-directory: app

jobs:
  pnpm-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: pnpm setup
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
          standalone: true
          package_json_file: app/package.json
          dest: ~/setup-pnpm
      - name: Build
        run: |
          pnpm install && pnpm build