name: Node.js Package

on:
  push:
    branches: 
      - test_build

defaults:
  run:
    working-directory: app
env:
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  pnpm-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup npmrc
        run: echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" > .npmrc
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
          standalone: true
          package_json_file: app/package.json
          dest: ~/setup-pnpm
      - name: Config pnpm
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER
      - name: Build
        run: |
          pnpm install
          pnpm build
      - name: create and publish versions
        uses: changesets/action@v1
        with:
          version: pnpm ci:version
          commit: "chore: update versions"
          title: "chore: update versions"
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}