name: "[CI] Release It"

on:
  workflow_dispatch:
    inputs:
      increment:
        description: |
          Version format is following: X.Y.Z.
          Increment selection:
            - X - major
            - Y - minor
            - Z - patch.
        required: true
        default: Z

defaults:
  run:
    working-directory: .github

jobs:
  release-tag-changelog:
    name: Release, Tag, Changelog
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Fetch tags and configure git
      run: |
        git fetch --prune --unshallow --tags
        git config --local user.name $GIT_USER_NAME
        git config --local user.email $GIT_USER_EMAIL
      env:
        GIT_USER_NAME: github-actions[bot]
        GIT_USER_EMAIL: 26793601+zerthmonk@users.noreply.github.com

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install release-it via Yarn
      run: |
        yarn global add release-it @release-it/conventional-changelog
        echo $(yarn global bin) >> $GITHUB_PATH
    - name: Parse increment
      run: |
        input=$(echo "${{ github.event.inputs.increment }}" | tr '[:lower:]' '[:upper:]')
        if [ "$input" == "X" ]; then
            increment="major"
        elif [ "$input" == "Y" ]; then
            increment="minor "
        elif [ "$input" == "Z" ]; then
            increment="patch"
        else
            echo "invalid value of input, should be one of X, Y, Z"; exit 1
        fi
        echo "increment=$increment" >> $GITHUB_ENV
    - name: Create tag/release, update CHANGELOG.md
      run: |
        release-it --config release-it.json --ci --increment=$increment
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}

permissions:
  contents: write
